import type { Metadata } from "next";
import Link from "next/link";
import { cookies } from "next/headers";
import "@fontsource-variable/nunito";

import Header from "./_components/Header/Header";
import "@/_styles/globals.css";
import { LIGHT_COLORS, DARK_COLORS } from "./constants";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const savedTheme = cookies().get("color-theme");
  const theme = savedTheme?.value || "light";
  const themeColors = theme === "light" ? LIGHT_COLORS : DARK_COLORS;

  return (
    <html lang="en" data-color-theme={theme} style={themeColors}>
      <body>
        <Header initialTheme={theme} />
        {children}
      </body>
    </html>
  );
}

